import = [
  "~/.config/alacritty/theme.toml"
]

[cursor]
unfocused_hollow = true
blink_interval = 500

[cursor.style]
shape = "Block"
blinking = "Always"

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 5
y = 10
	
[keyboard]
bindings = [
 { key = "V",     mods = "Command",       action = "Paste" },
 { key = "C",     mods = "Command",       action = "Copy" },
]
