[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x969896"
blue = "0xb4b7b4"
cyan = "0xa3685a"
green = "0x282a2e"
magenta = "0xe0e0e0"
red = "0xde935f"
white = "0xffffff"
yellow = "0x373b41"

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[cursor]
unfocused_hollow = true
blink_interval = 500
[cursor.style]
shape = "Block"
blinking = "Always"

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 5
y = 10
	
